Tickets/dm 26702
lsst-ts/ts_idl pull request #43
Opened 2020-10-09 21:21 UTC by colinwinslow

changes the build process such that it triggers the SalObj Conda job and has it use the just-built IDL Conda package.

Update IDL Conda job, so that builds are all marked as dev

2020-10-09 21:33 UTC, rbovill commented on Jenkinsfile.conda
> +                    build propagate: false, job: 'SalObj_Conda_package/tickets%2FDM-26702', parameters: [booleanParam(name: 'develop', value: true), booleanParam(name: 'buildCSCConda', value: true),
please update the branch to be 'develop' and not the ticket branch.  That should be the permanent state, until things change.

2020-10-09 21:34 UTC, rbovill requested changes
Please update the branch in call to build the salobj conda job.

2020-10-09 22:16 UTC, rbovill approved these changes
Updates look good to me.

2020-10-12 18:01 UTC, rbovill requested changes
Please squash and rebase

2020-10-16 23:19 UTC, tribeiro approved these changes
Looks good!

2020-10-16 23:59 UTC, rbovill approved these changes

2020-10-17 00:00 UTC, merged