Renamed Dome to MTDome.
lsst-ts/ts_idl pull request #46
Opened 2020-11-03 18:32 UTC by wvreeven

2020-11-03 19:05 UTC, r-owen approved these changes
Looks good.

2020-11-03 19:08 UTC, tribeiro commented
FYI, this change will break code elsewhere. I'd rather wait until we get closer to the release date to get this merged.

2020-11-03 19:15 UTC, tribeiro requested changes
FYI, this change will break code elsewhere... I was hopping we could wait until we get a clear date for the next xml release before doing this.

2020-11-12 13:20 UTC, tribeiro approved these changes

2020-11-12 13:24 UTC, merged